apiVersion: v1
kind: ConfigMap
metadata:
  name: mhs-config
data:
  # 日志开关
  config.json: |-
    {
      "server": {
        "host": "0.0.0.0",
        "port": "8888"
      },
      "log": {
        "enable": true,
        "request_header": false
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: myhttpserver
spec:
  terminationGracePeriodSeconds: 20
  containers:
    - name: myhttpserver
      image: lanceliu2022/myhttpserver:1.0

      resources:
        # QoS保证：Guaranteed
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 100Mi

      # 配置和代码分离
      volumeMounts:
        - name: mhs-config
          mountPath: /conf
          readOnly: true
      args:
        - -c
        - /conf/config.json
      ports:
      - name: liveness-port
        containerPort: 8888
        hostPort: 80

      # 优雅启动、探活
      startupProbe:
        httpGet:
          path: /healthz
          port: liveness-port
        failureThreshold: 30
        periodSeconds: 2
      livenessProbe:
        httpGet:
          path: /healthz
          port: liveness-port
        failureThreshold: 1
        periodSeconds: 10

      # 优雅终止
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "kill -SIGTERM `pidof myhttpserver`"]

  volumes:
  - name: mhs-config
    configMap:
      name: mhs-config
      defaultMode: 400
