#-------------------------------
#  HTTP服务器的配置文件
#-------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: myhttpserver-config
data:
  # 日志开关
  config.json: |-
    {
      "server": {
        "host": "0.0.0.0",
        "port": "8888"
      },
      "log": {
        "enable": true,
        "request_header": false
      }
    }
